# docker-compose.yml
version: '3'

services:
  apache:
    image: httpd:2.4
    ports:
      - "80:80"
      - "443:443"
    volumes:
      #- ./apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./apache/ssl:/usr/local/apache2/conf/ssl

  sinatra:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app/:/app
    command: ["bundle","exec","rackup","--host","0.0.0.0","--port","4567"]
    #ports:
    #  - "4567:4567"
